language: php

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php vendor/bin/phpunit tests
  - php vendor/bin/php-cs-fixer fix --dry-run --config .php_cs.dist -v
  - php vendor/bin/phpstan analyse

php:
  - 7.1
